spring.application.name=payment-service
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.cloud.gcp.firestore.project-id=${PROJECT_ID:travel2go-495007}
spring.cloud.gcp.firestore.database-id=travel2go-db

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

quote.token.secret=${QUOTE_TOKEN_SECRET}
quote.token.ttl-ms=900000

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
