package com.travel2go.backend.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.pdf.*;
import com.travel2go.backend.model.GlobalSettings;
import com.travel2go.backend.model.HolidayPackage;
import org.springframework.stereotype.Service;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URL;

@Service
public class PdfService {

    class PdfHeaderFooter extends PdfPageEventHelper {
        PdfTemplate total;
        BaseFont bf;
        HolidayPackage pkg;

        public PdfHeaderFooter(HolidayPackage pkg) {
            this.pkg = pkg;
        }

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            total = writer.getDirectContent().createTemplate(30, 16);
            try {
                bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
            } catch (Exception e) {}
        }

        @Override
        public void onStartPage(PdfWriter writer, Document document) {
            if (writer.getPageNumber() == 1 && pkg.getMedia() != null && pkg.getMedia().getThumbnailUrl() != null && !pkg.getMedia().getThumbnailUrl().isEmpty()) {
                try {
                    Image img = Image.getInstance(new URL(pkg.getMedia().getThumbnailUrl()));
                    img.setAbsolutePosition(0, document.getPageSize().getHeight() - 300);
                    img.scaleAbsolute(document.getPageSize().getWidth(), 300);
                    
                    PdfContentByte cb = writer.getDirectContentUnder();
                    cb.saveState();
                    PdfGState gs1 = new PdfGState();
                    gs1.setFillOpacity(0.15f); // Faded
                    cb.setGState(gs1);
                    cb.addImage(img);
                    cb.restoreState();
                } catch (Exception e) {
                    // Skip if image fails
                }
            }
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            
            // Footer text
            String text = "Page " + writer.getPageNumber() + " of ";
            cb.beginText();
            cb.setFontAndSize(bf, 10);
            cb.setColorFill(Color.GRAY);
            float textBase = document.bottom() - 10;
            cb.setTextMatrix(document.right() - 80, textBase);
            cb.showText(text);
            cb.endText();
            cb.addTemplate(total, document.right() - 80 + bf.getWidthPoint(text, 10), textBase);
            
            // Add branding to footer
            cb.beginText();
            cb.setFontAndSize(bf, 10);
            cb.setColorFill(Color.GRAY);
            cb.setTextMatrix(document.left(), textBase);
            cb.showText("Generated by Travel2Go");
            cb.endText();
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            total.beginText();
            total.setFontAndSize(bf, 10);
            total.setColorFill(Color.GRAY);
            total.setTextMatrix(0, 0);
            total.showText(String.valueOf(writer.getPageNumber()));
            total.endText();
        }
    }

    public byte[] generatePackagePdf(HolidayPackage pkg, GlobalSettings settings) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 40, 40, 60, 40);
        PdfWriter writer = PdfWriter.getInstance(document, baos);
        writer.setPageEvent(new PdfHeaderFooter(pkg));
        document.open();

        // Fonts
        Font brandFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 28, new Color(37, 99, 235)); // Blue-600
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Color.BLACK);
        Font subTitleFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 14, Color.DARK_GRAY);
        Font sectionHeaderFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, new Color(30, 64, 175)); // Blue-800
        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11, new Color(55, 65, 81));
        Font priceFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, new Color(16, 185, 129)); // Emerald-500
        Font priceWordsFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, Color.GRAY);

        // Travel2Go Branding
        Paragraph brand = new Paragraph("Travel2Go", brandFont);
        brand.setAlignment(Element.ALIGN_CENTER);
        brand.setSpacingAfter(30);
        document.add(brand);

        // Title
        Paragraph title = new Paragraph(pkg.getTitle(), titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(5);
        document.add(title);

        // Duration & Location
        Paragraph subtitle = new Paragraph(pkg.getDuration().getDays() + " Days / " + pkg.getDuration().getNights() + " Nights | " + pkg.getDestination(), subTitleFont);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        subtitle.setSpacingAfter(20);
        document.add(subtitle);
        
        // Pricing
        if (pkg.getPricing() != null) {
            long price = (long) pkg.getPricing().getFinalPrice();
            String currency = pkg.getPricing().getCurrency() != null ? pkg.getPricing().getCurrency() : "INR";
            
            PdfPTable priceTable = new PdfPTable(1);
            priceTable.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell();
            cell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
            cell.setBackgroundColor(new Color(240, 253, 244)); // Light green bg
            cell.setPadding(15);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            Paragraph pricePara = new Paragraph("Final Price: " + currency + " " + String.format("%,d", price), priceFont);
            pricePara.setAlignment(Element.ALIGN_CENTER);
            cell.addElement(pricePara);
            
            Paragraph wordsPara = new Paragraph("(" + NumberToWordsConverter.convert(price) + " " + currency + " Only)", priceWordsFont);
            wordsPara.setAlignment(Element.ALIGN_CENTER);
            cell.addElement(wordsPara);
            
            priceTable.addCell(cell);
            priceTable.setSpacingAfter(30);
            document.add(priceTable);
        }

        // Overview
        addSection(document, "Overview", stripHtml(pkg.getOverview()), sectionHeaderFont, normalFont);

        // Itinerary
        if (pkg.getItinerary() != null && !pkg.getItinerary().isEmpty()) {
            addSectionHeader(document, "Itinerary", sectionHeaderFont);
            for (HolidayPackage.ItineraryDay day : pkg.getItinerary()) {
                Paragraph dayTitle = new Paragraph("Day " + day.getDay() + " - " + day.getTitle(), FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, new Color(55, 65, 81)));
                dayTitle.setSpacingBefore(10);
                dayTitle.setSpacingAfter(4);
                document.add(dayTitle);
                
                Paragraph dayDesc = new Paragraph(stripHtml(day.getActivities()), normalFont);
                dayDesc.setSpacingAfter(10);
                document.add(dayDesc);
            }
        }

        // Inclusions/Exclusions
        if (pkg.getInclusions() != null && !pkg.getInclusions().isEmpty()) {
            addSection(document, "Inclusions", "• " + String.join("\n• ", pkg.getInclusions()), sectionHeaderFont, normalFont);
        }
        if (pkg.getExclusions() != null && !pkg.getExclusions().isEmpty()) {
            addSection(document, "Exclusions", "• " + String.join("\n• ", pkg.getExclusions()), sectionHeaderFont, normalFont);
        }

        // Special Notes
        if (pkg.getSpecialNotes() != null && !pkg.getSpecialNotes().isEmpty()) {
            addSection(document, "Important Notes & Conditions", stripHtml(pkg.getSpecialNotes()), sectionHeaderFont, normalFont);
        }

        document.close();
        return baos.toByteArray();
    }

    private void addSectionHeader(Document document, String title, Font headerFont) throws DocumentException {
        Paragraph header = new Paragraph(title, headerFont);
        header.setSpacingBefore(20);
        header.setSpacingAfter(8);
        document.add(header);
        
        // Add a subtle line under section header
        com.lowagie.text.pdf.draw.LineSeparator ls = new com.lowagie.text.pdf.draw.LineSeparator();
        ls.setLineColor(new Color(229, 231, 235)); // Gray-200
        ls.setLineWidth(1);
        document.add(new Chunk(ls));
    }

    private void addSection(Document document, String title, String content, Font headerFont, Font contentFont) throws DocumentException {
        addSectionHeader(document, title, headerFont);
        Paragraph body = new Paragraph(content, contentFont);
        body.setSpacingAfter(15);
        document.add(body);
    }

    private String stripHtml(String html) {
        if (html == null) return "";
        // Simple regex to strip HTML tags and decode basic entities
        return html.replaceAll("<[^>]*>", "")
                   .replaceAll("&nbsp;", " ")
                   .replaceAll("&amp;", "&")
                   .replaceAll("&quot;", "\"")
                   .replaceAll("&lt;", "<")
                   .replaceAll("&gt;", ">")
                   .replaceAll("&#39;", "'")
                   .trim();
    }
}
