package com.travel2go.backend.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.pdf.*;
import com.travel2go.backend.model.Booking;
import com.travel2go.backend.model.GlobalSettings;
import com.travel2go.backend.model.HolidayPackage;
import org.springframework.stereotype.Service;

import java.text.SimpleDateFormat;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URL;

@Service
public class PdfService {

    class PdfHeaderFooter extends PdfPageEventHelper {
        PdfTemplate total;
        BaseFont bf;
        HolidayPackage pkg;

        public PdfHeaderFooter(HolidayPackage pkg) {
            this.pkg = pkg;
        }

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            total = writer.getDirectContent().createTemplate(30, 16);
            try {
                bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
            } catch (Exception e) {}
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            
            // Footer text
            String text = "Page " + writer.getPageNumber() + " of ";
            cb.beginText();
            cb.setFontAndSize(bf, 10);
            cb.setColorFill(Color.GRAY);
            float textBase = document.bottom() - 10;
            cb.setTextMatrix(document.right() - 80, textBase);
            cb.showText(text);
            cb.endText();
            cb.addTemplate(total, document.right() - 80 + bf.getWidthPoint(text, 10), textBase);
            
            // Add branding to footer
            cb.beginText();
            cb.setFontAndSize(bf, 10);
            cb.setColorFill(Color.GRAY);
            cb.setTextMatrix(document.left(), textBase);
            cb.showText("Generated by Travel2Go");
            cb.endText();
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            total.beginText();
            total.setFontAndSize(bf, 10);
            total.setColorFill(Color.GRAY);
            total.setTextMatrix(0, 0);
            total.showText(String.valueOf(writer.getPageNumber() - 1));
            total.endText();
        }
    }

    public byte[] generatePackagePdf(HolidayPackage pkg, GlobalSettings settings, Booking booking) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 40, 40, 60, 40);
        PdfWriter writer = PdfWriter.getInstance(document, baos);
        writer.setPageEvent(new PdfHeaderFooter(pkg));
        document.open();

        // Fonts
        Font brandFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 28, new Color(37, 99, 235)); // Blue-600
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Color.BLACK);
        Font subTitleFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 14, Color.DARK_GRAY);
        Font sectionHeaderFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, new Color(30, 64, 175)); // Blue-800
        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11, new Color(55, 65, 81));
        Font priceFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, new Color(16, 185, 129)); // Emerald-500
        Font priceWordsFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, Color.GRAY);

        // Travel2Go Branding
        Paragraph brand = new Paragraph("Travel2Go", brandFont);
        brand.setAlignment(Element.ALIGN_CENTER);
        brand.setSpacingAfter(30);
        document.add(brand);

        // Title
        Paragraph title = new Paragraph(pkg.getTitle(), titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(5);
        document.add(title);

        // Duration & Location
        Paragraph subtitle = new Paragraph(pkg.getDuration().getDays() + " Days / " + pkg.getDuration().getNights() + " Nights | " + pkg.getDestination(), subTitleFont);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        subtitle.setSpacingAfter(20);
        document.add(subtitle);
        
        // Pricing
        if (pkg.getPricing() != null) {
            long price = (long) pkg.getPricing().getFinalPrice();
            String currency = pkg.getPricing().getCurrency() != null ? pkg.getPricing().getCurrency() : "INR";
            
            String priceLabel = "Final Price (per person): ";
            if (booking != null && booking.getFinalPrice() != null) {
                price = booking.getFinalPrice().longValue();
                int adults = booking.getAdults() != null ? booking.getAdults() : 1;
                int children = booking.getChildren() != null ? booking.getChildren() : 0;
                priceLabel = String.format("Final Price (for %d Adults, %d Children): ", adults, children);
            }
            
            PdfPTable priceTable = new PdfPTable(1);
            priceTable.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell();
            cell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
            cell.setBackgroundColor(new Color(240, 253, 244)); // Light green bg
            cell.setPadding(15);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            String formattedPrice = formatIndianCurrency(price);
            Paragraph pricePara = new Paragraph(priceLabel + currency + " " + formattedPrice, priceFont);
            pricePara.setAlignment(Element.ALIGN_CENTER);
            cell.addElement(pricePara);
            
            Paragraph wordsPara = new Paragraph("(" + NumberToWordsConverter.convert(price) + " " + currency + " Only)", priceWordsFont);
            wordsPara.setAlignment(Element.ALIGN_CENTER);
            cell.addElement(wordsPara);
            
            priceTable.addCell(cell);
            priceTable.setSpacingAfter(30);
            document.add(priceTable);
        }

        // Overview
        if (pkg.getOverview() != null && !pkg.getOverview().isEmpty()) {
            addRichTextSection(document, "Overview", pkg.getOverview(), sectionHeaderFont, normalFont);
        }

        // Itinerary
        if (pkg.getItinerary() != null && !pkg.getItinerary().isEmpty()) {
            addSectionHeader(document, "Itinerary", sectionHeaderFont);
            for (HolidayPackage.ItineraryDay day : pkg.getItinerary()) {
                Paragraph dayTitle = new Paragraph("Day " + day.getDay() + " - " + day.getTitle(), FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, new Color(55, 65, 81)));
                dayTitle.setSpacingBefore(10);
                dayTitle.setSpacingAfter(4);
                document.add(dayTitle);
                
                String[] acts = extractBulletPoints(day.getActivities());
                if (acts.length > 0) {
                    com.lowagie.text.List list = new com.lowagie.text.List(com.lowagie.text.List.UNORDERED);
                    list.setListSymbol("• ");
                    for (String act : acts) {
                        if (!act.trim().isEmpty()) {
                            ListItem item = new ListItem(act.trim(), normalFont);
                            item.setSpacingAfter(3);
                            list.add(item);
                        }
                    }
                    document.add(list);
                }
            }
        }

        // Inclusions/Exclusions
        if (pkg.getInclusions() != null && !pkg.getInclusions().isEmpty()) {
            addSection(document, "Inclusions", "• " + String.join("\n• ", pkg.getInclusions()), sectionHeaderFont, normalFont);
        }
        if (pkg.getExclusions() != null && !pkg.getExclusions().isEmpty()) {
            addSection(document, "Exclusions", "• " + String.join("\n• ", pkg.getExclusions()), sectionHeaderFont, normalFont);
        }

        // Special Notes
        if (pkg.getSpecialNotes() != null && !pkg.getSpecialNotes().isEmpty()) {
            addRichTextSection(document, "Special Notes", pkg.getSpecialNotes(), sectionHeaderFont, normalFont);
        }

        // Package Offered To
        if (booking != null) {
            addSectionHeader(document, "Package Offered To", sectionHeaderFont);

            SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy 'at' hh:mm a 'IST'");
            sdf.setTimeZone(java.util.TimeZone.getTimeZone("Asia/Kolkata"));
            String bookingDateStr = booking.getBookingDate() != null ? sdf.format(booking.getBookingDate()) : "N/A";

            com.lowagie.text.List userDetailsList = new com.lowagie.text.List(com.lowagie.text.List.UNORDERED);
            userDetailsList.setListSymbol("");
            
            ListItem nameItem = new ListItem("Name: " + booking.getFirstName() + " " + (booking.getLastName() != null ? booking.getLastName() : ""), normalFont);
            nameItem.setSpacingAfter(3);
            userDetailsList.add(nameItem);
            
            ListItem emailItem = new ListItem("Email: " + booking.getEmail(), normalFont);
            emailItem.setSpacingAfter(3);
            userDetailsList.add(emailItem);
            
            ListItem phoneItem = new ListItem("Phone: " + booking.getPhone(), normalFont);
            phoneItem.setSpacingAfter(3);
            userDetailsList.add(phoneItem);
            
            ListItem locationItem = new ListItem("Location: " + booking.getLocation(), normalFont);
            locationItem.setSpacingAfter(3);
            userDetailsList.add(locationItem);
            
            int adultsCount = booking.getAdults() != null ? booking.getAdults() : 1;
            int childrenCount = booking.getChildren() != null ? booking.getChildren() : 0;
            ListItem travelersItem = new ListItem(String.format("Travelers: %d Adults, %d Children", adultsCount, childrenCount), normalFont);
            travelersItem.setSpacingAfter(3);
            userDetailsList.add(travelersItem);

            String currency = (pkg.getPricing() != null && pkg.getPricing().getCurrency() != null) ? pkg.getPricing().getCurrency() : "INR";
            if (booking.getFinalPrice() != null) {
                ListItem basePriceItem = new ListItem(String.format("Base Price: %s %.2f", currency, booking.getBasePrice() != null ? booking.getBasePrice() : 0.0), normalFont);
                basePriceItem.setSpacingAfter(3);
                userDetailsList.add(basePriceItem);

                ListItem discountItem = new ListItem(String.format("Discount Applied: %.1f%%", booking.getDiscountPercentage() != null ? booking.getDiscountPercentage() : 0.0), normalFont);
                discountItem.setSpacingAfter(3);
                userDetailsList.add(discountItem);

                ListItem finalPriceItem = new ListItem(String.format("Final Calculated Price: %s %.2f", currency, booking.getFinalPrice()), normalFont);
                finalPriceItem.setSpacingAfter(3);
                userDetailsList.add(finalPriceItem);
            }
            
            ListItem dateItem = new ListItem("Date of Request: " + bookingDateStr, normalFont);
            dateItem.setSpacingAfter(3);
            userDetailsList.add(dateItem);
            
            document.add(userDetailsList);
        }

        // Terms & Conditions
        if (settings != null && settings.getTermsAndConditions() != null) {
            String termsText = stripHtml(settings.getTermsAndConditions());
            if (!termsText.isEmpty()) {
                document.add(new Chunk(new com.lowagie.text.pdf.draw.LineSeparator()));
                Paragraph termsHeader = new Paragraph("Terms & Conditions", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.GRAY));
                termsHeader.setSpacingBefore(20);
                termsHeader.setSpacingAfter(10);
                document.add(termsHeader);
                Paragraph termsBody = new Paragraph(termsText, FontFactory.getFont(FontFactory.HELVETICA, 9, Color.DARK_GRAY));
                document.add(termsBody);
            }
        }

        document.close();
        return baos.toByteArray();
    }

    private void addSectionHeader(Document document, String title, Font headerFont) throws DocumentException {
        Paragraph header = new Paragraph(title, headerFont);
        header.setSpacingBefore(20);
        header.setSpacingAfter(8);
        document.add(header);
        
        // Add a subtle line under section header
        com.lowagie.text.pdf.draw.LineSeparator ls = new com.lowagie.text.pdf.draw.LineSeparator();
        ls.setLineColor(new Color(229, 231, 235)); // Gray-200
        ls.setLineWidth(1);
        document.add(new Chunk(ls));
    }

    private void addSection(Document document, String title, String content, Font headerFont, Font contentFont) throws DocumentException {
        addSectionHeader(document, title, headerFont);
        Paragraph body = new Paragraph(content, contentFont);
        body.setSpacingAfter(15);
        document.add(body);
    }

    private void addRichTextSection(Document document, String title, String html, Font headerFont, Font normalFont) throws DocumentException {
        if (html == null || html.trim().isEmpty()) return;
        String cleanHtml = stripHtml(html).trim();
        if (cleanHtml.isEmpty()) return;
        
        addSectionHeader(document, title, headerFont);
        
        String processed = html.replaceAll("(?i)<li>", "• ")
                               .replaceAll("(?i)</li>", "\n")
                               .replaceAll("(?i)</p>", "\n")
                               .replaceAll("(?i)<br\\s*/?>", "\n")
                               .replaceAll("&nbsp;", " ")
                               .replaceAll("\u00A0", " ");
                               
        processed = stripHtml(processed); 
        
        String[] lines = processed.split("\\n");
        for (String line : lines) {
            String trimmed = line.trim();
            if (!trimmed.isEmpty()) {
                Paragraph p = new Paragraph(trimmed, normalFont);
                p.setSpacingAfter(6);
                document.add(p);
            }
        }
        
        // Add some extra space after the entire section
        Paragraph spacer = new Paragraph(" ", normalFont);
        spacer.setSpacingAfter(10);
        document.add(spacer);
    }

    private String[] extractBulletPoints(String html) {
        if (html == null) return new String[0];
        String processed = html.replaceAll("(?i)</li>", "\n")
                               .replaceAll("(?i)</p>", "\n")
                               .replaceAll("(?i)<br\\s*/?>", "\n");
        processed = stripHtml(processed);
        return processed.split("\\n");
    }

    private String stripHtml(String html) {
        if (html == null) return "";
        // Simple regex to strip HTML tags and decode basic entities
        return html.replaceAll("<[^>]*>", "")
                   .replaceAll("&nbsp;", " ")
                   .replaceAll("&amp;", "&")
                   .replaceAll("&quot;", "\"")
                   .replaceAll("&lt;", "<")
                   .replaceAll("&gt;", ">")
                   .replaceAll("&#39;", "'")
                   .trim();
    }

    private String formatIndianCurrency(long value) {
        String s = Long.toString(value);
        if (s.length() <= 3) return s;
        StringBuilder sb = new StringBuilder();
        sb.append(s.substring(s.length() - 3));
        int i = s.length() - 3;
        while (i > 0) {
            sb.insert(0, ",");
            int start = Math.max(0, i - 2);
            sb.insert(0, s.substring(start, i));
            i = start;
        }
        return sb.toString();
    }
}
