management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
server.port=${PORT:8080}

# Debug Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.travel2go=DEBUG
