spring.application.name=backend
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/holidaydb}

jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b294a08da1fecbb6e8b46990538c7b50b2}
jwt.expiration=86400000

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:placeholder}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:placeholder}
spring.security.oauth2.client.registration.google.scope=profile,email



# Mail configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:placeholder@gmail.com}
spring.mail.password=${MAIL_PASSWORD:placeholder}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google Cloud Storage Configuration
gcp.bucket.name=${GCP_BUCKET_NAME:travel2go-media-bucket}
