spring.application.name=backend
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.cloud.gcp.firestore.project-id=${PROJECT_ID:travel2go-495007}
spring.cloud.gcp.firestore.database-id=travel2go-db

jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b294a08da1fecbb6e8b46990538c7b50b2}
jwt.expiration=86400000

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:placeholder}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:placeholder}
spring.security.oauth2.client.registration.google.scope=profile,email

app.oauth2.redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:5173/oauth2/redirect}



# Mail configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:placeholder@gmail.com}
spring.mail.password=${MAIL_PASSWORD:placeholder}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google Cloud Storage Configuration
gcp.bucket.name=${GCP_BUCKET_NAME:travel2go-media-bucket}

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Twilio Configuration
twilio.account_sid=${TWILIO_ACCOUNT_SID:placeholder}
twilio.auth_token=${TWILIO_AUTH_TOKEN:placeholder}
twilio.phone_number=${TWILIO_PHONE_NUMBER:placeholder}
